typography_spectrum: 0.8516
color:
  brandColors:
    - '#000000'
    - '#343434'
    - '#bbbbbb'
    - '#8c8c8c'
    - '#fefefe'
  brandStrength: 0.08732544723898172
  lightness: 0.26293121511116624
  saturation: 0.5472485159989446
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.95224
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Alberto Krone-Martins
  email: algol@sim.ul.pt
name: theia
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Mission
    id: 3880b8f4-7d47-4cb9-98ad-e7303ea287b0
    type: content
  - name: Payload
    id: 2c59cc07-49db-4380-a9a5-9c262f3b6f7e
    type: content
favicon: null
title: Theia
description: the Universe in motion
purpose: []
