name: theia
favicon: null
layout_spectrum: 0.95224
typography_spectrum: 0.8516
title: 'Theia: the Universe in motion'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#343434'
    - '#bbbbbb'
    - '#8c8c8c'
    - '#fefefe'
  brandStrength: 0.08732544723898172
  lightness: 0.26293121511116624
  saturation: 0.5472485159989446
  rhythmicContrast: 0.25
purpose: []
