typography_spectrum: 0.8516
color:
  brandColors:
    - '#000000'
    - '#343434'
    - '#bbbbbb'
    - '#8c8c8c'
    - '#fefefe'
  brandStrength: 0.08732544723898172
  lightness: 0.26293121511116624
  saturation: 0.5472485159989446
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.95224
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Alberto Krone-Martins
  email: algol@sim.ul.pt
name: theia
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Theia
description: the Universe in motion
purpose: []
