typography_spectrum: 0.8516
color:
  brandColors:
    - '#000000'
    - '#343434'
    - '#bbbbbb'
    - '#8c8c8c'
    - '#fefefe'
  brandStrength: 0.08732544723898172
  lightness: 0.26293121511116624
  saturation: 0.5472485159989446
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.95224
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Alberto Krone-Martins
  email: algol@sim.ul.pt
name: theia
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Mission
    id: 3880b8f4-7d47-4cb9-98ad-e7303ea287b0
    type: content
  - name: Astrometry
    id: 2c59cc07-49db-4380-a9a5-9c262f3b6f7e
    type: content
  - name: Dark Matter
    id: 4b92fe10-6594-42d1-8a21-7001c773b4f6
    type: content
  - name: Exoplanets
    id: 60a454bb-f225-4407-8851-b8e7cbd6311e
    type: content
  - name: Legacy
    id: e8c1732c-bf2f-4902-b4cb-6098315dad81
    type: content
  - name: Heritage
    id: 0aaa2d42-4793-4b8d-b308-02c6d695741f
    type: content
favicon: null
title: Theia
description: the Universe in motion
purpose: []
