name: theia
favicon: null
layout_spectrum: 0.995121412910521
typography_spectrum: 0.17942248634062707
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.08732544723898172
  lightness: 0.26293121511116624
  saturation: 0.5472485159989446
  rhythmicContrast: 0.8313745914492756
purpose: []
